package com.voituri.ridesharing.domain;

import static com.voituri.ridesharing.domain.AssertUtils.zonedDataTimeSameInstant;
import static org.assertj.core.api.Assertions.assertThat;

public class RideAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRideAllPropertiesEquals(Ride expected, Ride actual) {
        assertRideAutoGeneratedPropertiesEquals(expected, actual);
        assertRideAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRideAllUpdatablePropertiesEquals(Ride expected, Ride actual) {
        assertRideUpdatableFieldsEquals(expected, actual);
        assertRideUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRideAutoGeneratedPropertiesEquals(Ride expected, Ride actual) {
        assertThat(expected)
            .as("Verify Ride auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRideUpdatableFieldsEquals(Ride expected, Ride actual) {
        assertThat(expected)
            .as("Verify Ride relevant properties")
            .satisfies(e -> assertThat(e.getStartLocation()).as("check startLocation").isEqualTo(actual.getStartLocation()))
            .satisfies(e -> assertThat(e.getEndLocation()).as("check endLocation").isEqualTo(actual.getEndLocation()))
            .satisfies(
                e ->
                    assertThat(e.getStartTime())
                        .as("check startTime")
                        .usingComparator(zonedDataTimeSameInstant)
                        .isEqualTo(actual.getStartTime())
            )
            .satisfies(
                e -> assertThat(e.getEndTime()).as("check endTime").usingComparator(zonedDataTimeSameInstant).isEqualTo(actual.getEndTime())
            )
            .satisfies(e -> assertThat(e.getRecurring()).as("check recurring").isEqualTo(actual.getRecurring()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRideUpdatableRelationshipsEquals(Ride expected, Ride actual) {
        assertThat(expected)
            .as("Verify Ride relationships")
            .satisfies(e -> assertThat(e.getMember()).as("check member").isEqualTo(actual.getMember()));
    }
}
